/**
 * Forge3D Integration Test Suite
 *
 * Performs end-to-end tests of the 3D generation pipeline:
 * 1. Health Check
 * 2. Project Creation
 * 3. Generation Trigger
 * 4. Poll for Completion
 * 5. FBX Download Verification
 * 6. Asset Registry Verification
 *
 * Usage: node src/forge3d/test-suite.js [--full]
 *
 * @author Marcus Daley (GrizzwaldHouse)
 * @date February 19, 2026
 */

import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const PORT = process.env.PORT || 3847;
const API_BASE = `http://localhost:${PORT}/api`;
const TEST_PROJECT_ID = 'test_suite_project';
const FULL_PIPELINE = process.argv.includes('--full');

let testsPassed = 0;
let testsFailed = 0;

function logResult(name, success, error = null) {
  if (success) {
    console.log(`[TEST-SUITE] [PASS] ${name}`);
    testsPassed++;
  } else {
    console.error(`[TEST-SUITE] [FAIL] ${name}${error ? ': ' + error : ''}`);
    testsFailed++;
  }
}

async function fetchJson(url, options = {}) {
  const response = await fetch(url, options);
  const data = await response.json();
  return { response, data };
}

async function runTests() {
  console.log(`[TEST-SUITE] Starting Forge3D Integration Tests (full=${FULL_PIPELINE})`);
  console.log(`[TEST-SUITE] API base: ${API_BASE}`);

  try {

    // Step 1: Health Check
    try {
      const { response } = await fetchJson(`${API_BASE}/health`);
      logResult('API Health Check', response.ok);
    } catch (e) {
      logResult('API Health Check', false, e.message);
    }

    // Step 2: Project Creation
    let projectId = TEST_PROJECT_ID;
    try {
      const { response, data } = await fetchJson(`${API_BASE}/forge3d/projects`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: 'Integration Test Project',
          description: 'Auto-generated by test-suite.js'
        })
      });
      if (response.ok && data.id) {
        projectId = data.id;
      }
      logResult('Project Creation', response.ok && Boolean(data.id));
    } catch (e) {
      logResult('Project Creation', false, e.message);
    }

    // Step 3: Trigger Generation
    let sessionId = null;
    console.log('[TEST-SUITE] Waiting for generation to start...');
    try {
      const { response, data } = await fetchJson(`${API_BASE}/forge3d/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          type: 'full',
          prompt: 'a simple low-poly wooden crate',
          projectId: projectId
        })
      });
      if (response.ok && data.sessionId) {
        sessionId = data.sessionId;
      }
      logResult(`Generation Triggered (Session: ${sessionId})`, response.ok && Boolean(sessionId));
    } catch (e) {
      logResult('Generation Trigger', false, e.message);
      return;
    }

    if (!sessionId) {
      console.error('[TEST-SUITE] No session ID returned — cannot continue polling.');
      return;
    }

    // Step 4: Poll for Completion
    console.log('[TEST-SUITE] Polling for completion (this may take 1-2 minutes)...');
    let state = 'idle';
    let attempts = 0;
    const maxAttempts = 60; // 2 minutes at 2s intervals

    while (state !== 'complete' && state !== 'failed' && attempts < maxAttempts) {
      await new Promise(r => setTimeout(r, 2000));
      try {
        const { response, data } = await fetchJson(`${API_BASE}/forge3d/status/${sessionId}`);
        if (response.ok) {
          state = data.state;
          const percent = data.progress ? data.progress.percent : 0;
          process.stdout.write(`\r[TEST-SUITE] Progress: ${percent}% [${state}]      `);
        }
        attempts++;
      } catch (e) {
        console.error(`\n[TEST-SUITE] Error during polling: ${e.message}`);
        break;
      }
    }
    console.log('');

    logResult('Generation Completion', state === 'complete');
    if (state !== 'complete') {
      console.error(`[TEST-SUITE] Final state was: ${state}`);
      return;
    }

    // Step 5: FBX Download Verification
    try {
      const response = await fetch(`${API_BASE}/forge3d/download/${sessionId}?format=fbx`);
      if (!response.ok) {
        logResult('FBX Download Verification', false, `HTTP ${response.status}`);
      } else {
        const buffer = await response.arrayBuffer();
        logResult('FBX Download Verification', buffer.byteLength > 0);
        console.log(`[TEST-SUITE] Downloaded FBX size: ${(buffer.byteLength / 1024).toFixed(2)} KB`);
      }
    } catch (e) {
      logResult('FBX Download Verification', false, e.message);
    }

    // Step 6: Asset Registry Verification
    try {
      const { response, data } = await fetchJson(`${API_BASE}/forge3d/assets/${projectId}`);
      const found = response.ok && Array.isArray(data) && data.some(a => a.name && a.name.includes('wooden_crate'));
      logResult('Asset Registry Verification', found);
    } catch (e) {
      logResult('Asset Registry Verification', false, e.message);
    }

  } catch (globalError) {
    console.error(`[TEST-SUITE] Global test failure: ${globalError.message}`);
  } finally {
    console.log('\n[TEST-SUITE] ---------------------------------------');
    console.log(`[TEST-SUITE] Test Suite Finished: ${testsPassed} passed, ${testsFailed} failed.`);
    console.log('[TEST-SUITE] ---------------------------------------');

    process.exit(testsFailed > 0 ? 1 : 0);
  }
}

runTests();
